### ISSUE TITLE
Tailwind

### ISSUE THREAD

**Issue by QuinnRachman** [NielsPoldervaart/electron-vite-solid-ts-boilerplate#4]
Can you add tailwind as an option?

Thanks :D

**Comment by QuinnRachman** [comment]
Please respond, this is very unprofessional!

**Comment by NielsPoldervaart** [comment]
> Can you add tailwind as an option?
> 
> Thanks :D
Leave me alone, You are stalking me for about a year now. I think it has been enough! I will not implement support for tailwind. If you want to have tailwind support you can always just add it yourself............



> Please respond, this is very unprofessional!
Ok bozo donut car!

**Comment by QuinnRachman** [comment]
That is not nice, I will report this to the elder council. GOOD DAY!
